apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: kong
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: {{ .Values.webapp.image }}
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets:
        {{- range .Values.webapp.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
